// Reservation codes such as LB-7KQ2MX (no 0/O, 1/I/L), as generated by the
// database. Mirrors private.normalize_reservation_code.
const CODE_BODY = /^[A-HJKMNP-Z2-9]{6}$/;

export function normalizeReservationCode(value: string): string | null {
  const compact = value.toUpperCase().replace(/[^A-Z0-9]/g, "");
  const body = compact.startsWith("LB") && compact.length === 8 ? compact.slice(2) : compact;
  return CODE_BODY.test(body) ? `LB-${body}` : null;
}

/** What a client sees about their booking; no contact data or notes. */
export interface Reservation {
  code: string;
  status: "agendado" | "concluido" | "faltou" | "cancelado";
  cancelledByClient: boolean;
  services: string[];
  stylistName: string;
  date: string;
  time: string;
  startAt: string;
  durationMinutes: number;
  price: number | null;
  cancelUntil: string;
  canCancel: boolean;
}

export type ReservationResult =
  | { ok: true; reservation: Reservation }
  | {
      ok: false;
      code: "not_found" | "not_active" | "too_late" | "invalid";
      message: string;
      reservation?: Reservation;
    };

export const reservationStatusLabels: Record<Reservation["status"], string> = {
  agendado: "Confirmada",
  concluido: "Atendimento realizado",
  faltou: "Não compareceu",
  cancelado: "Cancelada",
};
